swagger: "2.0"
info:
  version: "0.0.1"
  title: Treehouse API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /boids/:
    get:
      description: "This endpoint returns all boids available"
      operationId: "GetAllBoids"
      parameters: []
      responses:
        200:
          description: "An array of boids"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Boid"
      x-swagger-router-controller: "GetAllBoids"

    post:
      description: "Add a new Boid"
      operationId: "AddBoid"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "boid"
        description: "the Boid to be added"
        required: true
        schema:
          $ref: "#/definitions/Boid"
      responses:
        200:
          description: "Successful Boid add"
          schema:
            $ref: "#/definitions/AddResponse"
      x-swagger-router-controller: "AddBoid"

  /swagger:
    x-swagger-pipe: swagger_raw

  /boid/{id}:
    get:
      description: "Retrieve a single boid by id"
      operationId: "FindBoidById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the boid to get"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Boid response"
          schema:
            $ref: "#/definitions/Boid"
      x-swagger-router-controller: "FindBoidById"
    delete:
      description: "Delete a boid by Id"
      operationId: "DeleteBoidById"
      parameters:
      - name: "id"
        in: "path"
        description: "id of the plyer to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        204:
          description: "boid deleted"
      x-swagger-router-controller: "DeleteBoidById"

    put:
      description: "Update a single boid by id"
      operationId: "UpdateBoidById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of the boid being updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "updated_boid"
        in: "body"
        description: "the updated boid"
        required: true
        schema:
          $ref: "#/definitions/Boid"
      responses:
        200:
          description: "Boid updated"
          schema:
            $ref: "#/definitions/Boid"
        400:
          description: "An error has occurred!"
      x-swagger-router-controller: "UpdateBoidById"

# complex objects have schema definitions
definitions:
  Boid:
    type: "object"
    properties:
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
      name:
        type: "string"
        description: "Boid name"
      speed:
        type: "integer"
        description: "Boid speed stat"
      strength:
        type: "integer"
        description: "Boid strength stat"
      shot:
        type: "integer"
        description: "Boid shooting stat"
      nation:
        type: "string"
        description: "Boid home nation"
      position:
        type: "string"
        description: "Boid position"
      age:
        type: "integer"
        description: "Boid age"

  AddResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Id of the boid added"
